[package]
name = 'LPCoin'
version = '1.0.0'

[dependencies]
AptosFramework = {git = "https://github.com/movemntdev/aptos-core.git", subdir = "aptos-move/framework/aptos-framework", rev = "testnet"}
AptosStdlib = {git = "https://github.com/movemntdev/aptos-core.git", subdir = "aptos-move/framework/aptos-stdlib/", rev = "testnet"}

[addresses]
std = "0x1"
razor_resource = "0x8511115e91e7f6bbb50cd51ee5469666a2e06eb041bbcac2544ce6b8d6b02ba1"
