services:
  subnet:
    build:
      context: ..
      dockerfile: ./movement/Dockerfile
      target: subnet
    expose:
      - 8080
      - 8081
      - 9650

  localnet:
    build:
      context: ..
      dockerfile: ./movement/Dockerfile
      target: localnet
    expose:
    - 8080
    - 8081
    - 9650

  installer:
    build: 
      context: ..
      dockerfile: ./movement/Dockerfile
      target: installer

  dev:
    build:
      context: ..
      dockerfile: ./movement/Dockerfile
      target: dev
    stdin_open: true  # Keep STDIN open even if not attached
    tty: true  # Allocate a pseudo-TTY
      

