[package]
name = "m2-contracts"
version = "0.0.1"

[dependencies]
Sui = { local = "./deps/sui-framework" }

[addresses]
razor = "0x0"
sui = "0x2"
std = "0x1"

deployer = "0x8ff0045977079db4863e169b3efb37f5f0cb8beb477128288b7ea66ecdf92c6d"
