[package]
name = 'Coins'
version = '1.0.0'

[dependencies]
AptosFramework = {git = "https://github.com/movemntdev/aptos-core.git", subdir = "aptos-move/framework/aptos-framework", rev = "testnet"}
AptosStdlib = {git = "https://github.com/movemntdev/aptos-core.git", subdir = "aptos-move/framework/aptos-stdlib/", rev = "testnet"}

[addresses]
std = "0x1"
razor = "0xcf85ab29b66bbb7a0e955413a84e6bc7e2648dae0658f94cd5e667f484efa4a5"